
title: S Ramprasath
first_name: Ramprasath
last_name: S
lang: en
url: https://srampras.github.io
markdown: GFM
# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

navbar_fixed: true
footer_fixed: true

# Dimensions
max_width: 960px

github_username: srampras, srini229
scholar_userid: https://scholar.google.com/citations?user=mtpx4_YAAAAJ
orcid_id: https://orcid.org/0000-0001-9487-9340
publons_id: # your ID on Publons
research_gate_profile: # your profile on ResearchGate
work_url: https://www.ee.iitm.ac.in/faculty/profile/ramprasath
wikidata_id: # your wikidata id
dblp_url: # your DBLP profile url
stackoverflow_id: #your stackoverflow id
